# GITHUB_REPOSITORY - The owner and repository name. For example, octocat/Hello-World.
# https://docs.github.com/en/actions/learn-github-actions/environment-variables

name: Docker Image

on:
  push:
    tags:
      - '*'

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # See https://github.com/docker/build-push-action/blob/master/docs/advanced/tags-labels.md
      - name: Docker Meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          #
          # list of Docker images to use as base name for tags
          images: |
            ghcr.io/${{ github.repository }}
          # generate Docker tags based on the following events/attributes
          tags: |
            type=ref,event=tag

      - name: Set Up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # See https://github.com/docker/login-action
      - name: Log In To The GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # See https://github.com/docker/build-push-action/blob/master/docs/advanced/tags-labels.md
      - name: Build And Push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          file: docker/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

